spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ccs?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 10101010
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf-8
      continue-on-error: false
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: debug
  file:
    name: ccs.log
  charset:
    console: utf-8
    file: utf-8
server:
  port: 8080
