spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ccs?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 10101010
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf-8
      continue-on-error: false
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rbmq
    password: 10101010
  jackson:
    serialization:
      '[FAIL_ON_EMPTY_BEANS]': false
logging:
  level:
    root: error
  file:
    name: ccs.log
  charset:
    console: utf-8
    file: utf-8
server:
  port: 8080
